### PR TITLE
tools to manipulate SDOs and PDOs

### PR DESCRIPTION
**Pull request by jimy-byerley**
This PR is to repropose #48 answering #40, because I messed up the git branch on my repo and broke the last PR
Now my branch should be clean

### CODE REVIEW

**Comment by jimy-byerley** [comment]
merges are missing, and examples still need to be updated, but I think the features are ready for your review :)

**Comment by jamwaffles** [comment]
34 changed files and `+2,141 −1,630` changes doesn't seem right. At first glance it looks like a rebase gone wrong?

**Comment by jimy-byerley** [comment]
I think it's been rebased before your simplification of `SlaveRef`. Merging the master branch into this may fix that :thinking:  (me playing with the history of commits really wasn't a good idea ;) )

**Comment by jimy-byerley** [comment]
Yes that's it, I started this branch before the change in `SlaveRef` and then merged it into the branch:  [d089037](https://github.com/ethercrab-rs/ethercrab/pull/50/commits/d089037eb911fa758768dbd4b5f290635c2ad64e)](https://github.com/ethercrab-rs/ethercrab/pull/50/commits/d089037eb911fa758768dbd4b5f290635c2ad64e)
So most of the changes reported here are exactly from that merge (plus some conflictx fixes)

**Comment by jamwaffles** [comment]
See https://github.com/ethercrab-rs/ethercrab/issues/40#issuecomment-1635995356

**Pull request closed without merging**
